### ISSUE TITLE
Apps?

### ISSUE THREAD

**Issue by monroemann** [breakdiving/tosfairness#35]
Some websites have apps.  Some apps have websites.  Some websites don't have apps.  Some apps don't have websites.  So we need to figure out how to add those four categories:

Apps
Apps with websites
Websites
Websites with apps

**Comment by taratip** [comment]
We can add another field in Contracts called categories. So I'm thinking to have another table only for Company. And it has association with Contracts table. One company can have many contracts. One contract belongs to one company.

**Comment by monroemann** [comment]
That makes sense.  Many contracts belong to one company.  One company HAS MANY contracts.  Good thinking!

**Comment by monroemann** [comment]
How do we solve the problem of some companies having an app, some having a website, and some having both (but with the same name)?  For example: Chase.com is the website, and Chase also has an app.  While they are both similar and related, they likely have different terms of service agreements.
