### ISSUE TITLE
Waitlist

### ISSUE THREAD

**Issue by monroemann** [breakdiving/tosfairness#37]
I tested out the 'contracts' page, and I added a fake company called Bible and website www.erasethis.com

It got added to the 'waitlist' but... now it's also listed on the main list of companies by contract.  That may be okay, but I think that it should say "WAITING TO BE REVIEWED" if it's been added, but no one has yet reviewed it.  

Thoughts?

**Comment by monroemann** [comment]
Also:  
https://gyazo.com/dc2ab6a705a0355e85d35261ce1acf0d

Since each company will have different contracts, how will this page play out?  Will there be one master 'company' page with multiple entries for different contracts?

**Comment by taratip** [comment]
Maybe we can show flash sign on add saying 'Waiting to be reviewed.'

To display company with different contracts, I'll change it to show the name of a company and list every contracts of the company. 

Let me know what you think.

**Comment by monroemann** [comment]
Do you mean using "Flash"?  Or a ruby on rails 'flash'?  I think a flash would be fine, but if there's a way to make it clear that it's waiting to be reviewed without having to click on it, that would be ideal.  This way, admin users could also easily see which contracts still have not yet been reviewed.
