### ISSUE TITLE
ratings

### ISSUE THREAD

**Issue by monroemann** [breakdiving/tosfairness#46]
if you click on rating scale in dropdown, you'll see that what you implemented is close but not exact.

1. historical fairness is not a number entered by admin.  it is calculated based on average of the bill of rights 1 - 50 score of all versions of that agreement, transmuted into a 1 to 10 scale.  (note that requires that the app find any contracts with the same name and bundle them together by date)
2. historical user rating is not added by admin.  it is calculated by the average of all user ratings of all versions of that contract, transmuted into a 1 to 10 scale.
3. public placement is 20points
4. we got rid of historical transparency when we last spoke on the phone, but perhaps i didn't make that clear

**Comment by taratip** [comment]
I did remove the historical transparency. I don't know why you still see it. And all of historical rating cannot be entered by admin. Was wondering if you did migration?
